apiVersion: apps/v1
kind: Deployment
metadata:
  name: automationweb
  labels:
    app: automationweb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: automationweb
  template:
    metadata:
      labels:
        app: automationweb
    spec:
      containers:
      - name: automationweb
        image: roche12/automationtools-automationweb:latest
        imagePullPolicy: Always
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        ports:
        - containerPort: 7000
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Production
        - name: AUTOMATION_HANGFIREAPI
          value: http://automationhangfireapi:5000/api/job/
        - name: BROWSER_LISTENERAPI
          value: http://192.168.100.22:5001/open-browser
        volumeMounts:
        - name: automation-data
          mountPath: /watched/AutomationData
      volumes:
      - name: automation-data
        persistentVolumeClaim:
          claimName: automation-data-pvc