apiVersion: apps/v1
kind: Deployment
metadata:
  name: automationweb
  labels:
    app: automationweb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: automationweb
  template:
    metadata:
      labels:
        app: automationweb
    spec:
      containers:
      - name: automationweb
        image: roche12/automationtools-automationweb:latest
        imagePullPolicy: Always
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        ports:
        - containerPort: 7000
        volumeMounts:
        - name: automation-data
          mountPath: /watched/AutomationData
        readinessProbe:
          httpGet:
            path: /
            port: 7000
          initialDelaySeconds: 5
          periodSeconds: 10
      volumes:
      - name: automation-data
        persistentVolumeClaim:
          claimName: automation-data-pvc