apiVersion: apps/v1
kind: Deployment
metadata:
  name: automationhangfireapi
  labels:
    app: automationhangfireapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: automationhangfireapi
  template:
    metadata:
      labels:
        app: automationhangfireapi
    spec:
      containers:
      - name: automationhangfireapi
        image: roche12/automationtools-automationhangfireapi:latest
        imagePullPolicy: Always
        resources:
          requests:
            memory: "512m"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "2"
        ports:
        - containerPort: 8080
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Development
        - name: HANGFIRE_REDIS_CONNECTION
          value: redis.redis.svc.cluster.local:6379
        volumeMounts:
        - name: automation-data
          mountPath: /watched/AutomationData
      volumes:
      - name: automation-data
        persistentVolumeClaim:
          claimName: automation-data-pvc