apiVersion: v1
kind: Service
metadata:
  name: automationhangfireapi
spec:
  selector:
    app: automationhangfireapi
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
  type: ClusterIP
  sessionAffinity: ClientIP