apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: automation-cluster
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/rochesantiago/RTP_CD_Deploy.git
    targetRevision: master
    path: deploy/
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  sources:
    - path: deploy/automationweb/application.yaml
    - path: deploy/automationhangfireapi/application.yaml
    - path: deploy/hpa/application.yaml
    - path: deploy/ingress/application.yaml
    - path: deploy/networkpolicy/application.yaml
    - path: deploy/pvc/application.yaml
    - path: deploy/redis/application.yaml
    