apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: automation-cluster
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  sources:
    - repoURL: https://github.com/rochesantiago/RTP_CD_Deploy.git
      targetRevision: master
      path: deploy/automationweb
    - repoURL: https://github.com/rochesantiago/RTP_CD_Deploy.git
      targetRevision: master
      path: deploy/automationhangfireapi
    - repoURL: https://github.com/rochesantiago/RTP_CD_Deploy.git
      targetRevision: master
      path: deploy/hpa
    - repoURL: https://github.com/rochesantiago/RTP_CD_Deploy.git
      targetRevision: master
      path: deploy/ingress
    - repoURL: https://github.com/rochesantiago/RTP_CD_Deploy.git
      targetRevision: master
      path: deploy/networkpolicy
    - repoURL: https://github.com/rochesantiago/RTP_CD_Deploy.git
      targetRevision: master
      path: deploy/pvc
    - repoURL: https://github.com/rochesantiago/RTP_CD_Deploy.git
      targetRevision: master
      path: deploy/redis