apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: automationweb-ingress
spec:
  rules:
  - host: automationweb.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: automationweb
            port:
              number: 7000