apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pvc-automation
  namespace: argocd
spec:
  project: default
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/rochesantiago/RTP_CD_Deploy.git
    targetRevision: master
    path: deploy/pvc